source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Tutorial2' do
pod 'Alamofire', '~> 1.3'
pod 'SwiftyJSON', '~> 2.2.1'
end

target 'Tutorial2Tests' do

end

